crds:
  install: true
  keep: false

global:
  domain: argocd.local

configs:
  params:
    server.insecure: true

server:
  service:
    type: ${service_type}

  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi

controller:
  resources:
    requests:
      cpu: 100m
      memory: 384Mi
    limits:
      cpu: 1000m
      memory: 768Mi

repoServer:
  resources:
    requests:
      cpu: 50m
      memory: 192Mi
    limits:
      cpu: 500m
      memory: 512Mi

applicationSet:
  enabled: false

notifications:
  enabled: false

dex:
  enabled: false

redis:
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi
