apiVersion: v2
name: django-app
description: Django-застосунок з теми 4, розгорнутий у EKS (образ з ECR, ConfigMap, LoadBalancer, HPA)
type: application
version: 0.1.0
appVersion: "1.0.0"

keywords:
  - django
  - eks
  - lesson-7
